import React,{useMemo,useState}from'react';
import{ShieldCheck,Menu,X,Phone,Mail,MapPin,CheckCircle2,Star,Send,BriefcaseBusiness,Camera,Car,Users,Lock,Award,GraduationCap,Building2}from'lucide-react';
import{company,nav,services,personnel,compliance,testimonials,clientTypes,careers,leaders}from'./siteData.js';
const iconMap={Manned:Users,Estate:Building2,Corporate:ShieldCheck,Event:Users,VIP:Award,Access:Lock,CCTV:Camera,Patrol:Car,Security:BriefcaseBusiness,Risk:ShieldCheck};
function Logo(){return <div className="logo-wrap"><div className="logo-shield"><span className="eye">◉</span><span className="logo-text">SPL</span></div><div><strong>SPEEDMEN</strong><small>PROTECTION LIMITED</small></div></div>}
function Header(){const[open,setOpen]=useState(false);return <header className="site-header"><Logo/><button className="menu-btn" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{nav.map(l=><a key={l} href={'#'+l.toLowerCase().replaceAll(' ','-')}>{l}</a>)}<a className="nav-cta" href="#request">Request Service</a></nav></header>}
function RequestForm(){const[form,setForm]=useState({name:'',phone:'',email:'',org:'',service:'Manned Guarding',location:'',guards:'',start:'',duration:'',property:'',risk:'Not sure',message:''});const msg=useMemo(()=>encodeURIComponent(`Hello Speedmen Protection Limited, I want to request security service.\nName: ${form.name}\nPhone: ${form.phone}\nEmail: ${form.email}\nOrganisation/Estate/Company: ${form.org}\nService Needed: ${form.service}\nLocation: ${form.location}\nNumber of Guards: ${form.guards}\nPreferred Start Date: ${form.start}\nDuration: ${form.duration}\nProperty Type: ${form.property}\nRisk Level: ${form.risk}\nMessage: ${form.message}`),[form]);const update=e=>setForm({...form,[e.target.name]:e.target.value});return <section id="request" className="form-section"><div><p className="eyebrow">Request Security Service</p><h2>Tell us what you need. We will respond promptly.</h2><p>Use this form for guards, patrol, CCTV monitoring, event security, VIP protection or a risk assessment. It opens WhatsApp with your request already prepared.</p></div><form onSubmit={e=>{e.preventDefault();window.open(`https://wa.me/${company.phone}?text=${msg}`,'_blank')}}>{['name','phone','email','org','location','guards','start','duration','property'].map(k=><input key={k} name={k} placeholder={k==='org'?'Organisation / Estate / Company':k==='guards'?'Number of Guards Required':k==='start'?'Preferred Start Date':k[0].toUpperCase()+k.slice(1)} value={form[k]} onChange={update}/>) }<select name="service" value={form.service} onChange={update}>{services.map(s=><option key={s.name}>{s.name}</option>)}</select><select name="risk" value={form.risk} onChange={update}><option>Low</option><option>Medium</option><option>High</option><option>Not sure</option></select><textarea name="message" placeholder="Message / Special Instruction" value={form.message} onChange={update}/><button className="primary" type="submit"><Send size={18}/> Submit to WhatsApp</button></form></section>}
function Hero(){return <section id="home" className="hero"><div className="hero-copy"><p className="eyebrow">NSCDC Licensed • Fully Insured • Compliance Focused</p><h1>Swift Response.<br/><span>Strong Protection.</span><br/>Total Peace of Mind.</h1><p>Professional private security solutions backed by trained personnel, modern security awareness, strict supervision and a culture of discipline and integrity.</p><div className="hero-actions"><a className="primary" href="#request">Request Security Service</a><a className="secondary" href={`https://wa.me/${company.phone}`}>Chat on WhatsApp</a></div></div><div className="guard-card"><div className="guard male"></div><div className="guard female"></div></div></section>}
function Services(){return <section id="security-services" className="section"><p className="eyebrow">Security Services</p><h2>Security solutions designed around your risk</h2><div className="grid services">{services.map(s=>{const key=s.name.split(' ')[0];const Icon=iconMap[key]||ShieldCheck;return <article id={s.slug} key={s.name}><Icon/><h3>{s.name}</h3><p>{s.summary}</p><ul>{s.details.map(d=><li key={d}><CheckCircle2 size={16}/>{d}</li>)}</ul><a href="#request">Request this service</a></article>})}</div></section>}
function About(){return <section id="about-us" className="split light"><div><p className="eyebrow">About Us</p><h2>Built for disciplined protection</h2><p>Speedmen Protection Limited was established to provide disciplined, reliable and professional private security services for individuals, estates, businesses, events and corporate institutions.</p><p>The company combines trained personnel, strict supervision, modern security awareness and quick response to protect lives, property and peace of mind.</p></div><div className="mission-cards"><article><h3>Mission</h3><p>To protect people, property and business operations through trained personnel, modern systems and proactive risk management.</p></article><article><h3>Vision</h3><p>To become one of Nigeria's most trusted private security companies, recognised for professionalism, discipline and excellent service.</p></article><article><h3>Core Values</h3><p>Discipline, integrity, vigilance, confidentiality, professionalism, loyalty and rapid response.</p></article></div></section>}
function Compliance(){return <section id="compliance" className="section compliance"><p className="eyebrow">Licensing, Insurance and Compliance</p><h2>Responsible security. Professional compliance.</h2><div className="grid badges">{compliance.map(b=><article key={b}><Award/><h3>{b}</h3><p>Our operations are designed around legal compliance, ethical conduct, staff discipline, client confidentiality and proper incident documentation.</p></article>)}</div></section>}
function Personnel(){return <section className="section"><p className="eyebrow">Personnel Categories</p><h2>Choose the right security grade for your environment</h2><div className="grid personnel">{personnel.map(p=><article key={p.name}><GraduationCap/><h3>{p.name}</h3><strong>{p.qualification}</strong><p>{p.summary}</p></article>)}</div><p className="note">All personnel undergo recruitment screening, background checks, training, uniform discipline, supervisor monitoring and continuous performance evaluation.</p></section>}
function Projects(){return <section id="projects" className="section projects"><p className="eyebrow">Projects and Clients Served</p><h2>Trusted across different security environments</h2><div className="grid smallcards">{clientTypes.map(x=><article key={x}>{x}</article>)}</div></section>}
function Testimonials(){return <section className="section"><p className="eyebrow">Testimonials</p><h2>What clients say</h2><div className="grid testimonials">{testimonials.map(t=><article key={t.name}><div>{Array.from({length:5}).map((_,i)=><Star key={i} fill="currentColor" size={16}/>)}</div><p>"{t.quote}"</p><strong>{t.name}</strong></article>)}</div></section>}
function Careers(){return <section id="careers" className="split careers"><div><p className="eyebrow">Careers</p><h2>Build a career in professional security</h2><p>Speedmen seeks disciplined, honest, physically fit and responsible people who want to build a career in private security.</p><ul>{careers.map(x=><li key={x}><CheckCircle2 size={17}/>{x}</li>)}</ul><a className="primary" href="#request">Apply Now</a></div><div className="team-illustration"></div></section>}
function Team(){return <section id="management-team" className="section"><p className="eyebrow">Management Team</p><h2>Leadership built on discipline and trust</h2><div className="grid team">{leaders.map(x=><article key={x}><div className="avatar"></div><h3>{x}</h3><p>Experienced leadership focused on client protection, operational discipline, staff training and service excellence.</p></article>)}</div></section>}
function Contact(){return <section id="contact-us" className="split contact"><div><p className="eyebrow">Contact Us</p><h2>Contact Speedmen Protection Limited</h2><p><MapPin/> {company.address}</p><p><Phone/> {company.phoneDisplay}</p><p><Mail/> {company.email}</p><a className="primary" href="#request">Request Security Service</a></div><div className="map">Speedmen Protection Limited<br/>Ushafa, Bwari, Abuja</div></section>}
export default function App(){return <div><Header/><main><Hero/><section className="trustbar">{['24/7 Protection','Rapid Response','Trained Personnel','Advanced Technology','Trust and Integrity'].map(t=><div key={t}><ShieldCheck/><strong>{t}</strong><small>Always on guard</small></div>)}</section><Services/><About/><Compliance/><Personnel/><RequestForm/><Projects/><Testimonials/><Careers/><Team/><Contact/></main><footer><Logo/><p>{company.tagline}</p><p>Copyright 2026 Speedmen Protection Limited. All Rights Reserved.</p></footer></div>}